# Site settings
title: Morejump Android Developer
description: "A blog about MoreJump ..."
baseurl: "morejump.github.io" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: MoreJump
user_title: MoreJump - Android Developer
email: luuvanthaoepu@gmail.com
github_username:  morejump
linkedin_public_url: morejump # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: https://avatars.githubusercontent.com/morejump

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/morejump
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: mjgenerator
    url: https://www.npmjs.com/package/mjgenerator
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
